### ISSUE TITLE
Add Provider Subtypes enumeration

### ISSUE THREAD

**Issue by thebecwar** [thebecwar/VirtualDiskInterop#22]

**Comment by FaustoNascimento** [comment]
Documentation with possible values here:

https://msdn.microsoft.com/en-us/library/windows/desktop/dd323674(v=vs.85).aspx

I'd just say... since I'd then also use this enum for creating virtual disks where the caller passes a value from this enum, maybe it's best to call it something that makes a bit more sense than ProviderSubtype. Maybe something like... VirtualDiskType?

**Comment by thebecwar** [comment]
I think that `VirtualDiskType` is too similar to `VirtualStorageType` so I went with `ProviderSpecificSubtype` instead. Commit: 325ae6c283b078e56715a32f092f1571f740a450
